name: Package EHS Sign Form Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install MSYS2
      run: |
        choco install msys2
        refreshenv
        C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
        C:\tools\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-cairo mingw-w64-x86_64-gdk-pixbuf2 mingw-w64-x86_64-pango"
        echo "export PATH=/c/msys64/mingw64/bin:$PATH" >> $GITHUB_ENV

    - name: Package with PyInstaller
      run: |
        pyinstaller --onefile --add-data "static;static" --add-data "templates;templates" signapp.py

    - name: List Dist Directory
      run: |
        dir dist

    - name: Verify Executable
      shell: powershell
      run: |
        if (Test-Path "dist/signapp.exe") {
          Write-Output "Executable created successfully."
        } else {
          Write-Error "Executable not found!"
          exit 1
        }

    - name: Upload the package
      uses: actions/upload-artifact@v2
      with:
        name: packaged-app
        path: dist/signapp.exe
